github: metadata

remote_theme: dieghernan/chulapa

# A. Site Settings / SEO options
locale: "en-US"
title: "Daily Muse"
title_separator: " | "
subtitle: "A Minimalistic Daily Dose of Inspiration"
description: "Daily Muse provides a clean, minimalistic space for your daily dose of inspiration."
url: ""
baseurl: ""
repository: "2026chell/Daily-Muse"
words_per_minute: 200
timezone: "America/Denver"

# SEO images and social
og_image: ""
twitter_site: ""
author:
  name: "2026chell"
  avatar: ""

# FontAwesome settings
fa_version: "6"
fa_kit_code: ""
fa_v4_support: false

# Google Analytics settings
gtag_id: ""
analytics_id: ""

# Search providers
search:
  provider: fusejs
  label: "Search"
  landing_page: "/search"
  maxwords: 30
  show_attrib: true
  algolia_logo: true

google_cse_id: ""

algolia:
  application_id: ""
  index_name: ""
  search_only_api_key: ""

comments:
  provider: ""
  disqus_shortname: ""

# B. Navigation
navbar:
  style: ""
  expand: "md"
  brand:
    title: "Home"
    url: ""
  nav:
    - title: "Blog"
      url: "/blog/"
    - title: "Cheatsheets"
      url: "/cheatsheets"
    - title: "Extras"
      child:
        - title: "Tags"
          url: "/tags"
        - title: "Categories"
          url: "/categories"
        - title: "Archive"
          url: "/archive"
        - title: "Current skin"
          url: "/current-skin"
    - title: "Docs"
      url: "https://dieghernan.github.io/chulapa/docs/01-install"
    - title: "Use this template"
      url: "https://github.com/dieghernan/chulapa-101/generate"

footer:
  links:
    - label: "Repo on Github"
      icon: "fab fa-github"
      url: "https://github.com/dieghernan/chulapa-101"
    - label: "RSS"
      icon: "fa fa-rss"
      url: "./atom.xml"
  copyright: ""

# C. Theme Settings
chulapa-skin:
  highlight: ""
  skin: ""
  autothemer: true
  vars:
    primary: "lightskyblue"

# D. Jekyll Defaults and Collections
paginate: 4
paginate_path: "/blog/page:num/"
paginator_maxnum: 3

collections:
  cheatsheet:
    output: true
    permalink: "/cheatsheets/:name"

defaults:
  - scope:
      path: ""
    values:
      layout: "default"
      header_type: "base"
      include_on_search: false
  - scope:
      path: ""
      type: "posts"
    values:
      header_type: "post"
      include_on_search: true
      include_on_feed: true
  - scope:
      path: ""
      type: "cheatsheet"
    values:
      header_type: "hero"
      include_on_search: true

compress_html:
  clippings: all
  blanklines: true

plugins:
  - jekyll-github-metadata
  - jekyll-paginate
  - jekyll-include-cache
  - jekyll-sitemap
  - jekyll-remote-theme

exclude:
  - "LICENSE"
  - "README.md"
  - "Gemfile"
  - "vendor"

include:
  - "_pages"

markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false
